remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

title: "Jun's Blog"
description: "Industrial AI and Robotics by Jun Hyojae"
url: "https://junresearch.github.io"
baseurl: ""

markdown: kramdown

plugins:
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      toc: true
      toc_sticky: true
